### PR TITLE
Fix - start automatically

### LINKED ISSUE #63: Start automatically - doesnt seem to be working any longer
Afternoon, I've been using your TabCarousel for a few years now for simple digital signage. (Has been working great for my needs thank you for all your efforts). Just recently - my users are complaining that the screen is sticking on one page rather than flipping through the tabs opened as expected. Maybe a change in Chromium or some kind of update has caused this option to fail. Wondered if there was going to be any fixing of that?  Aside from starting automatically, it works just as expected. I am using TabCarousel on a raspberry pie (64 bit) running the latest raspbianOS debian BookWorm and using the Chromium browser:

TabCarousel version 1.0.0
Chromium version 124.0.6367.73 running on Debian 12 (64 Bit) 

I start the browser with a bash script in kiosk mode on boot up - so there is typically no user interaction with the screen, it just opens the browser with specific tabs set and if the carousel is set to start automatically, it used to just run - refreshing every 5 minutes. Any suggestions greatly appreciated and thanks again for a great extension.

### PR DESCRIPTION
**Pull request by madhur**
Attempt to fix #63

### CODE REVIEW

File: src/javascripts/background.js [hunk 1]
```diff
@@ -12,6 +12,7 @@ import { defaults } from './shared.js';
 import { constants } from './shared.js';
 
 chrome.runtime.onInstalled.addListener(({reason}) => {
+    console.log(reason);
```
Comment (benjaminoakes) [inline src/javascripts/background.js:15]: Should this be removed?

**Review by benjaminoakes — APPROVED** [review]
No blockers

Thanks for this!

File: src/javascripts/background.js (hunk 1 above)
Comment (madhur) [reply src/javascripts/background.js]: Addressed
